// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataContent.proto

package cn.tim.xchat.core.model;

public final class DataContentSerializer {
  private DataContentSerializer() {}
  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
            (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DataContentOrBuilder extends
          // @@protoc_insertion_point(interface_extends:DataContent)
          com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint32 action = 1;</code>
     */
    boolean hasAction();
    /**
     * <code>required uint32 action = 1;</code>
     */
    int getAction();

    /**
     * <code>optional string senderId = 2;</code>
     */
    boolean hasSenderId();
    /**
     * <code>optional string senderId = 2;</code>
     */
    java.lang.String getSenderId();
    /**
     * <code>optional string senderId = 2;</code>
     */
    com.google.protobuf.ByteString
    getSenderIdBytes();

    /**
     * <code>optional string receiveId = 3;</code>
     */
    boolean hasReceiveId();
    /**
     * <code>optional string receiveId = 3;</code>
     */
    java.lang.String getReceiveId();
    /**
     * <code>optional string receiveId = 3;</code>
     */
    com.google.protobuf.ByteString
    getReceiveIdBytes();

    /**
     * <code>optional int32 timestamp = 4;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>optional int32 timestamp = 4;</code>
     */
    int getTimestamp();

    /**
     * <code>optional .DataContent.ChatMessage chatMessage = 5;</code>
     */
    boolean hasChatMessage();
    /**
     * <code>optional .DataContent.ChatMessage chatMessage = 5;</code>
     */
    cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessage getChatMessage();
    /**
     * <code>optional .DataContent.ChatMessage chatMessage = 5;</code>
     */
    cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessageOrBuilder getChatMessageOrBuilder();
  }
  /**
   * Protobuf type {@code DataContent}
   */
  public  static final class DataContent extends
          com.google.protobuf.GeneratedMessageV3 implements
          // @@protoc_insertion_point(message_implements:DataContent)
          DataContentOrBuilder {
    private static final long serialVersionUID = 0L;
    // Use DataContent.newBuilder() to construct.
    private DataContent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DataContent() {
      senderId_ = "";
      receiveId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DataContent(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
              com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              action_ = input.readUInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              senderId_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              receiveId_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              timestamp_ = input.readInt32();
              break;
            }
            case 42: {
              cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessage.Builder subBuilder = null;
              if (((bitField0_ & 0x00000010) != 0)) {
                subBuilder = chatMessage_.toBuilder();
              }
              chatMessage_ = input.readMessage(cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessage.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(chatMessage_);
                chatMessage_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000010;
              break;
            }
            default: {
              if (!parseUnknownField(
                      input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return cn.tim.xchat.core.model.DataContentSerializer.internal_static_DataContent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return cn.tim.xchat.core.model.DataContentSerializer.internal_static_DataContent_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      cn.tim.xchat.core.model.DataContentSerializer.DataContent.class, cn.tim.xchat.core.model.DataContentSerializer.DataContent.Builder.class);
    }

    public interface ChatMessageOrBuilder extends
            // @@protoc_insertion_point(interface_extends:DataContent.ChatMessage)
            com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required uint32 type = 1;</code>
       */
      boolean hasType();
      /**
       * <code>required uint32 type = 1;</code>
       */
      int getType();

      /**
       * <code>optional string text = 2;</code>
       */
      boolean hasText();
      /**
       * <code>optional string text = 2;</code>
       */
      java.lang.String getText();
      /**
       * <code>optional string text = 2;</code>
       */
      com.google.protobuf.ByteString
      getTextBytes();

      /**
       * <code>optional string at = 3;</code>
       */
      boolean hasAt();
      /**
       * <code>optional string at = 3;</code>
       */
      java.lang.String getAt();
      /**
       * <code>optional string at = 3;</code>
       */
      com.google.protobuf.ByteString
      getAtBytes();

      /**
       * <code>optional string url = 4;</code>
       */
      boolean hasUrl();
      /**
       * <code>optional string url = 4;</code>
       */
      java.lang.String getUrl();
      /**
       * <code>optional string url = 4;</code>
       */
      com.google.protobuf.ByteString
      getUrlBytes();

      /**
       * <code>optional string reply = 5;</code>
       */
      boolean hasReply();
      /**
       * <code>optional string reply = 5;</code>
       */
      java.lang.String getReply();
      /**
       * <code>optional string reply = 5;</code>
       */
      com.google.protobuf.ByteString
      getReplyBytes();
    }
    /**
     * Protobuf type {@code DataContent.ChatMessage}
     */
    public  static final class ChatMessage extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:DataContent.ChatMessage)
            ChatMessageOrBuilder {
      private static final long serialVersionUID = 0L;
      // Use ChatMessage.newBuilder() to construct.
      private ChatMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private ChatMessage() {
        text_ = "";
        at_ = "";
        url_ = "";
        reply_ = "";
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private ChatMessage(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                bitField0_ |= 0x00000001;
                type_ = input.readUInt32();
                break;
              }
              case 18: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000002;
                text_ = bs;
                break;
              }
              case 26: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000004;
                at_ = bs;
                break;
              }
              case 34: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000008;
                url_ = bs;
                break;
              }
              case 42: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000010;
                reply_ = bs;
                break;
              }
              default: {
                if (!parseUnknownField(
                        input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
                  e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return cn.tim.xchat.core.model.DataContentSerializer.internal_static_DataContent_ChatMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return cn.tim.xchat.core.model.DataContentSerializer.internal_static_DataContent_ChatMessage_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessage.class, cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessage.Builder.class);
      }

      private int bitField0_;
      public static final int TYPE_FIELD_NUMBER = 1;
      private int type_;
      /**
       * <code>required uint32 type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required uint32 type = 1;</code>
       */
      public int getType() {
        return type_;
      }

      public static final int TEXT_FIELD_NUMBER = 2;
      private volatile java.lang.Object text_;
      /**
       * <code>optional string text = 2;</code>
       */
      public boolean hasText() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string text = 2;</code>
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            text_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string text = 2;</code>
       */
      public com.google.protobuf.ByteString
      getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int AT_FIELD_NUMBER = 3;
      private volatile java.lang.Object at_;
      /**
       * <code>optional string at = 3;</code>
       */
      public boolean hasAt() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string at = 3;</code>
       */
      public java.lang.String getAt() {
        java.lang.Object ref = at_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            at_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string at = 3;</code>
       */
      public com.google.protobuf.ByteString
      getAtBytes() {
        java.lang.Object ref = at_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          at_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int URL_FIELD_NUMBER = 4;
      private volatile java.lang.Object url_;
      /**
       * <code>optional string url = 4;</code>
       */
      public boolean hasUrl() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional string url = 4;</code>
       */
      public java.lang.String getUrl() {
        java.lang.Object ref = url_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            url_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string url = 4;</code>
       */
      public com.google.protobuf.ByteString
      getUrlBytes() {
        java.lang.Object ref = url_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          url_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int REPLY_FIELD_NUMBER = 5;
      private volatile java.lang.Object reply_;
      /**
       * <code>optional string reply = 5;</code>
       */
      public boolean hasReply() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional string reply = 5;</code>
       */
      public java.lang.String getReply() {
        java.lang.Object ref = reply_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            reply_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string reply = 5;</code>
       */
      public com.google.protobuf.ByteString
      getReplyBytes() {
        java.lang.Object ref = reply_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          reply_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasType()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
              throws java.io.IOException {
        if (((bitField0_ & 0x00000001) != 0)) {
          output.writeUInt32(1, type_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, text_);
        }
        if (((bitField0_ & 0x00000004) != 0)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 3, at_);
        }
        if (((bitField0_ & 0x00000008) != 0)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 4, url_);
        }
        if (((bitField0_ & 0x00000010) != 0)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 5, reply_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) != 0)) {
          size += com.google.protobuf.CodedOutputStream
                  .computeUInt32Size(1, type_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, text_);
        }
        if (((bitField0_ & 0x00000004) != 0)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, at_);
        }
        if (((bitField0_ & 0x00000008) != 0)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, url_);
        }
        if (((bitField0_ & 0x00000010) != 0)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, reply_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
          return true;
        }
        if (!(obj instanceof cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessage)) {
          return super.equals(obj);
        }
        cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessage other = (cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessage) obj;

        if (hasType() != other.hasType()) return false;
        if (hasType()) {
          if (getType()
                  != other.getType()) return false;
        }
        if (hasText() != other.hasText()) return false;
        if (hasText()) {
          if (!getText()
                  .equals(other.getText())) return false;
        }
        if (hasAt() != other.hasAt()) return false;
        if (hasAt()) {
          if (!getAt()
                  .equals(other.getAt())) return false;
        }
        if (hasUrl() != other.hasUrl()) return false;
        if (hasUrl()) {
          if (!getUrl()
                  .equals(other.getUrl())) return false;
        }
        if (hasReply() != other.hasReply()) return false;
        if (hasReply()) {
          if (!getReply()
                  .equals(other.getReply())) return false;
        }
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasType()) {
          hash = (37 * hash) + TYPE_FIELD_NUMBER;
          hash = (53 * hash) + getType();
        }
        if (hasText()) {
          hash = (37 * hash) + TEXT_FIELD_NUMBER;
          hash = (53 * hash) + getText().hashCode();
        }
        if (hasAt()) {
          hash = (37 * hash) + AT_FIELD_NUMBER;
          hash = (53 * hash) + getAt().hashCode();
        }
        if (hasUrl()) {
          hash = (37 * hash) + URL_FIELD_NUMBER;
          hash = (53 * hash) + getUrl().hashCode();
        }
        if (hasReply()) {
          hash = (37 * hash) + REPLY_FIELD_NUMBER;
          hash = (53 * hash) + getReply().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessage parseFrom(
              java.nio.ByteBuffer data)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessage parseFrom(
              java.nio.ByteBuffer data,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessage parseFrom(
              com.google.protobuf.ByteString data)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessage parseFrom(
              com.google.protobuf.ByteString data,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessage parseFrom(byte[] data)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessage parseFrom(
              byte[] data,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessage parseFrom(java.io.InputStream input)
              throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
      }
      public static cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessage parseFrom(
              java.io.InputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessage parseDelimitedFrom(java.io.InputStream input)
              throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
      }
      public static cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessage parseDelimitedFrom(
              java.io.InputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessage parseFrom(
              com.google.protobuf.CodedInputStream input)
              throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
      }
      public static cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessage parseFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessage prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
              com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code DataContent.ChatMessage}
       */
      public static final class Builder extends
              com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
              // @@protoc_insertion_point(builder_implements:DataContent.ChatMessage)
              cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessageOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
          return cn.tim.xchat.core.model.DataContentSerializer.internal_static_DataContent_ChatMessage_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
          return cn.tim.xchat.core.model.DataContentSerializer.internal_static_DataContent_ChatMessage_fieldAccessorTable
                  .ensureFieldAccessorsInitialized(
                          cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessage.class, cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessage.Builder.class);
        }

        // Construct using cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessage.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          type_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          text_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          at_ = "";
          bitField0_ = (bitField0_ & ~0x00000004);
          url_ = "";
          bitField0_ = (bitField0_ & ~0x00000008);
          reply_ = "";
          bitField0_ = (bitField0_ & ~0x00000010);
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
          return cn.tim.xchat.core.model.DataContentSerializer.internal_static_DataContent_ChatMessage_descriptor;
        }

        @java.lang.Override
        public cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessage getDefaultInstanceForType() {
          return cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessage.getDefaultInstance();
        }

        @java.lang.Override
        public cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessage build() {
          cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessage result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessage buildPartial() {
          cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessage result = new cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessage(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            result.type_ = type_;
            to_bitField0_ |= 0x00000001;
          }
          if (((from_bitField0_ & 0x00000002) != 0)) {
            to_bitField0_ |= 0x00000002;
          }
          result.text_ = text_;
          if (((from_bitField0_ & 0x00000004) != 0)) {
            to_bitField0_ |= 0x00000004;
          }
          result.at_ = at_;
          if (((from_bitField0_ & 0x00000008) != 0)) {
            to_bitField0_ |= 0x00000008;
          }
          result.url_ = url_;
          if (((from_bitField0_ & 0x00000010) != 0)) {
            to_bitField0_ |= 0x00000010;
          }
          result.reply_ = reply_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessage) {
            return mergeFrom((cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessage)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessage other) {
          if (other == cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessage.getDefaultInstance()) return this;
          if (other.hasType()) {
            setType(other.getType());
          }
          if (other.hasText()) {
            bitField0_ |= 0x00000002;
            text_ = other.text_;
            onChanged();
          }
          if (other.hasAt()) {
            bitField0_ |= 0x00000004;
            at_ = other.at_;
            onChanged();
          }
          if (other.hasUrl()) {
            bitField0_ |= 0x00000008;
            url_ = other.url_;
            onChanged();
          }
          if (other.hasReply()) {
            bitField0_ |= 0x00000010;
            reply_ = other.reply_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          if (!hasType()) {
            return false;
          }
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
          cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessage parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessage) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private int type_ ;
        /**
         * <code>required uint32 type = 1;</code>
         */
        public boolean hasType() {
          return ((bitField0_ & 0x00000001) != 0);
        }
        /**
         * <code>required uint32 type = 1;</code>
         */
        public int getType() {
          return type_;
        }
        /**
         * <code>required uint32 type = 1;</code>
         */
        public Builder setType(int value) {
          bitField0_ |= 0x00000001;
          type_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required uint32 type = 1;</code>
         */
        public Builder clearType() {
          bitField0_ = (bitField0_ & ~0x00000001);
          type_ = 0;
          onChanged();
          return this;
        }

        private java.lang.Object text_ = "";
        /**
         * <code>optional string text = 2;</code>
         */
        public boolean hasText() {
          return ((bitField0_ & 0x00000002) != 0);
        }
        /**
         * <code>optional string text = 2;</code>
         */
        public java.lang.String getText() {
          java.lang.Object ref = text_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              text_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string text = 2;</code>
         */
        public com.google.protobuf.ByteString
        getTextBytes() {
          java.lang.Object ref = text_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            text_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string text = 2;</code>
         */
        public Builder setText(
                java.lang.String value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000002;
          text_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string text = 2;</code>
         */
        public Builder clearText() {
          bitField0_ = (bitField0_ & ~0x00000002);
          text_ = getDefaultInstance().getText();
          onChanged();
          return this;
        }
        /**
         * <code>optional string text = 2;</code>
         */
        public Builder setTextBytes(
                com.google.protobuf.ByteString value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000002;
          text_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object at_ = "";
        /**
         * <code>optional string at = 3;</code>
         */
        public boolean hasAt() {
          return ((bitField0_ & 0x00000004) != 0);
        }
        /**
         * <code>optional string at = 3;</code>
         */
        public java.lang.String getAt() {
          java.lang.Object ref = at_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              at_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string at = 3;</code>
         */
        public com.google.protobuf.ByteString
        getAtBytes() {
          java.lang.Object ref = at_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            at_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string at = 3;</code>
         */
        public Builder setAt(
                java.lang.String value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000004;
          at_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string at = 3;</code>
         */
        public Builder clearAt() {
          bitField0_ = (bitField0_ & ~0x00000004);
          at_ = getDefaultInstance().getAt();
          onChanged();
          return this;
        }
        /**
         * <code>optional string at = 3;</code>
         */
        public Builder setAtBytes(
                com.google.protobuf.ByteString value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000004;
          at_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object url_ = "";
        /**
         * <code>optional string url = 4;</code>
         */
        public boolean hasUrl() {
          return ((bitField0_ & 0x00000008) != 0);
        }
        /**
         * <code>optional string url = 4;</code>
         */
        public java.lang.String getUrl() {
          java.lang.Object ref = url_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              url_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string url = 4;</code>
         */
        public com.google.protobuf.ByteString
        getUrlBytes() {
          java.lang.Object ref = url_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            url_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string url = 4;</code>
         */
        public Builder setUrl(
                java.lang.String value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000008;
          url_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string url = 4;</code>
         */
        public Builder clearUrl() {
          bitField0_ = (bitField0_ & ~0x00000008);
          url_ = getDefaultInstance().getUrl();
          onChanged();
          return this;
        }
        /**
         * <code>optional string url = 4;</code>
         */
        public Builder setUrlBytes(
                com.google.protobuf.ByteString value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000008;
          url_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object reply_ = "";
        /**
         * <code>optional string reply = 5;</code>
         */
        public boolean hasReply() {
          return ((bitField0_ & 0x00000010) != 0);
        }
        /**
         * <code>optional string reply = 5;</code>
         */
        public java.lang.String getReply() {
          java.lang.Object ref = reply_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              reply_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string reply = 5;</code>
         */
        public com.google.protobuf.ByteString
        getReplyBytes() {
          java.lang.Object ref = reply_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            reply_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string reply = 5;</code>
         */
        public Builder setReply(
                java.lang.String value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000010;
          reply_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string reply = 5;</code>
         */
        public Builder clearReply() {
          bitField0_ = (bitField0_ & ~0x00000010);
          reply_ = getDefaultInstance().getReply();
          onChanged();
          return this;
        }
        /**
         * <code>optional string reply = 5;</code>
         */
        public Builder setReplyBytes(
                com.google.protobuf.ByteString value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000010;
          reply_ = value;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:DataContent.ChatMessage)
      }

      // @@protoc_insertion_point(class_scope:DataContent.ChatMessage)
      private static final cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessage DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessage();
      }

      public static cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessage getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<ChatMessage>
              PARSER = new com.google.protobuf.AbstractParser<ChatMessage>() {
        @java.lang.Override
        public ChatMessage parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
          return new ChatMessage(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<ChatMessage> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<ChatMessage> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessage getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int ACTION_FIELD_NUMBER = 1;
    private int action_;
    /**
     * <code>required uint32 action = 1;</code>
     */
    public boolean hasAction() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required uint32 action = 1;</code>
     */
    public int getAction() {
      return action_;
    }

    public static final int SENDERID_FIELD_NUMBER = 2;
    private volatile java.lang.Object senderId_;
    /**
     * <code>optional string senderId = 2;</code>
     */
    public boolean hasSenderId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string senderId = 2;</code>
     */
    public java.lang.String getSenderId() {
      java.lang.Object ref = senderId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          senderId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string senderId = 2;</code>
     */
    public com.google.protobuf.ByteString
    getSenderIdBytes() {
      java.lang.Object ref = senderId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        senderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECEIVEID_FIELD_NUMBER = 3;
    private volatile java.lang.Object receiveId_;
    /**
     * <code>optional string receiveId = 3;</code>
     */
    public boolean hasReceiveId() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string receiveId = 3;</code>
     */
    public java.lang.String getReceiveId() {
      java.lang.Object ref = receiveId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          receiveId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string receiveId = 3;</code>
     */
    public com.google.protobuf.ByteString
    getReceiveIdBytes() {
      java.lang.Object ref = receiveId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        receiveId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 4;
    private int timestamp_;
    /**
     * <code>optional int32 timestamp = 4;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional int32 timestamp = 4;</code>
     */
    public int getTimestamp() {
      return timestamp_;
    }

    public static final int CHATMESSAGE_FIELD_NUMBER = 5;
    private cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessage chatMessage_;
    /**
     * <code>optional .DataContent.ChatMessage chatMessage = 5;</code>
     */
    public boolean hasChatMessage() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional .DataContent.ChatMessage chatMessage = 5;</code>
     */
    public cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessage getChatMessage() {
      return chatMessage_ == null ? cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessage.getDefaultInstance() : chatMessage_;
    }
    /**
     * <code>optional .DataContent.ChatMessage chatMessage = 5;</code>
     */
    public cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessageOrBuilder getChatMessageOrBuilder() {
      return chatMessage_ == null ? cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessage.getDefaultInstance() : chatMessage_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasAction()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasChatMessage()) {
        if (!getChatMessage().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeUInt32(1, action_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, senderId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, receiveId_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeInt32(4, timestamp_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeMessage(5, getChatMessage());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
                .computeUInt32Size(1, action_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, senderId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, receiveId_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt32Size(4, timestamp_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
                .computeMessageSize(5, getChatMessage());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof cn.tim.xchat.core.model.DataContentSerializer.DataContent)) {
        return super.equals(obj);
      }
      cn.tim.xchat.core.model.DataContentSerializer.DataContent other = (cn.tim.xchat.core.model.DataContentSerializer.DataContent) obj;

      if (hasAction() != other.hasAction()) return false;
      if (hasAction()) {
        if (getAction()
                != other.getAction()) return false;
      }
      if (hasSenderId() != other.hasSenderId()) return false;
      if (hasSenderId()) {
        if (!getSenderId()
                .equals(other.getSenderId())) return false;
      }
      if (hasReceiveId() != other.hasReceiveId()) return false;
      if (hasReceiveId()) {
        if (!getReceiveId()
                .equals(other.getReceiveId())) return false;
      }
      if (hasTimestamp() != other.hasTimestamp()) return false;
      if (hasTimestamp()) {
        if (getTimestamp()
                != other.getTimestamp()) return false;
      }
      if (hasChatMessage() != other.hasChatMessage()) return false;
      if (hasChatMessage()) {
        if (!getChatMessage()
                .equals(other.getChatMessage())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasAction()) {
        hash = (37 * hash) + ACTION_FIELD_NUMBER;
        hash = (53 * hash) + getAction();
      }
      if (hasSenderId()) {
        hash = (37 * hash) + SENDERID_FIELD_NUMBER;
        hash = (53 * hash) + getSenderId().hashCode();
      }
      if (hasReceiveId()) {
        hash = (37 * hash) + RECEIVEID_FIELD_NUMBER;
        hash = (53 * hash) + getReceiveId().hashCode();
      }
      if (hasTimestamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + getTimestamp();
      }
      if (hasChatMessage()) {
        hash = (37 * hash) + CHATMESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getChatMessage().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.tim.xchat.core.model.DataContentSerializer.DataContent parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.tim.xchat.core.model.DataContentSerializer.DataContent parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.tim.xchat.core.model.DataContentSerializer.DataContent parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.tim.xchat.core.model.DataContentSerializer.DataContent parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.tim.xchat.core.model.DataContentSerializer.DataContent parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.tim.xchat.core.model.DataContentSerializer.DataContent parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.tim.xchat.core.model.DataContentSerializer.DataContent parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static cn.tim.xchat.core.model.DataContentSerializer.DataContent parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.tim.xchat.core.model.DataContentSerializer.DataContent parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.tim.xchat.core.model.DataContentSerializer.DataContent parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.tim.xchat.core.model.DataContentSerializer.DataContent parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static cn.tim.xchat.core.model.DataContentSerializer.DataContent parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.tim.xchat.core.model.DataContentSerializer.DataContent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
              ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DataContent}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:DataContent)
            cn.tim.xchat.core.model.DataContentSerializer.DataContentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return cn.tim.xchat.core.model.DataContentSerializer.internal_static_DataContent_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return cn.tim.xchat.core.model.DataContentSerializer.internal_static_DataContent_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        cn.tim.xchat.core.model.DataContentSerializer.DataContent.class, cn.tim.xchat.core.model.DataContentSerializer.DataContent.Builder.class);
      }

      // Construct using cn.tim.xchat.core.model.DataContentSerializer.DataContent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
              com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getChatMessageFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        action_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        senderId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        receiveId_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        timestamp_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        if (chatMessageBuilder_ == null) {
          chatMessage_ = null;
        } else {
          chatMessageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return cn.tim.xchat.core.model.DataContentSerializer.internal_static_DataContent_descriptor;
      }

      @java.lang.Override
      public cn.tim.xchat.core.model.DataContentSerializer.DataContent getDefaultInstanceForType() {
        return cn.tim.xchat.core.model.DataContentSerializer.DataContent.getDefaultInstance();
      }

      @java.lang.Override
      public cn.tim.xchat.core.model.DataContentSerializer.DataContent build() {
        cn.tim.xchat.core.model.DataContentSerializer.DataContent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.tim.xchat.core.model.DataContentSerializer.DataContent buildPartial() {
        cn.tim.xchat.core.model.DataContentSerializer.DataContent result = new cn.tim.xchat.core.model.DataContentSerializer.DataContent(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.action_ = action_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.senderId_ = senderId_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.receiveId_ = receiveId_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.timestamp_ = timestamp_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          if (chatMessageBuilder_ == null) {
            result.chatMessage_ = chatMessage_;
          } else {
            result.chatMessage_ = chatMessageBuilder_.build();
          }
          to_bitField0_ |= 0x00000010;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
              com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
              com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.tim.xchat.core.model.DataContentSerializer.DataContent) {
          return mergeFrom((cn.tim.xchat.core.model.DataContentSerializer.DataContent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.tim.xchat.core.model.DataContentSerializer.DataContent other) {
        if (other == cn.tim.xchat.core.model.DataContentSerializer.DataContent.getDefaultInstance()) return this;
        if (other.hasAction()) {
          setAction(other.getAction());
        }
        if (other.hasSenderId()) {
          bitField0_ |= 0x00000002;
          senderId_ = other.senderId_;
          onChanged();
        }
        if (other.hasReceiveId()) {
          bitField0_ |= 0x00000004;
          receiveId_ = other.receiveId_;
          onChanged();
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasChatMessage()) {
          mergeChatMessage(other.getChatMessage());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasAction()) {
          return false;
        }
        if (hasChatMessage()) {
          if (!getChatMessage().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        cn.tim.xchat.core.model.DataContentSerializer.DataContent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.tim.xchat.core.model.DataContentSerializer.DataContent) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int action_ ;
      /**
       * <code>required uint32 action = 1;</code>
       */
      public boolean hasAction() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required uint32 action = 1;</code>
       */
      public int getAction() {
        return action_;
      }
      /**
       * <code>required uint32 action = 1;</code>
       */
      public Builder setAction(int value) {
        bitField0_ |= 0x00000001;
        action_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 action = 1;</code>
       */
      public Builder clearAction() {
        bitField0_ = (bitField0_ & ~0x00000001);
        action_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object senderId_ = "";
      /**
       * <code>optional string senderId = 2;</code>
       */
      public boolean hasSenderId() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string senderId = 2;</code>
       */
      public java.lang.String getSenderId() {
        java.lang.Object ref = senderId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            senderId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string senderId = 2;</code>
       */
      public com.google.protobuf.ByteString
      getSenderIdBytes() {
        java.lang.Object ref = senderId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          senderId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string senderId = 2;</code>
       */
      public Builder setSenderId(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        senderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string senderId = 2;</code>
       */
      public Builder clearSenderId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        senderId_ = getDefaultInstance().getSenderId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string senderId = 2;</code>
       */
      public Builder setSenderIdBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        senderId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object receiveId_ = "";
      /**
       * <code>optional string receiveId = 3;</code>
       */
      public boolean hasReceiveId() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string receiveId = 3;</code>
       */
      public java.lang.String getReceiveId() {
        java.lang.Object ref = receiveId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            receiveId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string receiveId = 3;</code>
       */
      public com.google.protobuf.ByteString
      getReceiveIdBytes() {
        java.lang.Object ref = receiveId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          receiveId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string receiveId = 3;</code>
       */
      public Builder setReceiveId(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        receiveId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string receiveId = 3;</code>
       */
      public Builder clearReceiveId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        receiveId_ = getDefaultInstance().getReceiveId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string receiveId = 3;</code>
       */
      public Builder setReceiveIdBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        receiveId_ = value;
        onChanged();
        return this;
      }

      private int timestamp_ ;
      /**
       * <code>optional int32 timestamp = 4;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional int32 timestamp = 4;</code>
       */
      public int getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>optional int32 timestamp = 4;</code>
       */
      public Builder setTimestamp(int value) {
        bitField0_ |= 0x00000008;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 timestamp = 4;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000008);
        timestamp_ = 0;
        onChanged();
        return this;
      }

      private cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessage chatMessage_;
      private com.google.protobuf.SingleFieldBuilderV3<
              cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessage, cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessage.Builder, cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessageOrBuilder> chatMessageBuilder_;
      /**
       * <code>optional .DataContent.ChatMessage chatMessage = 5;</code>
       */
      public boolean hasChatMessage() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional .DataContent.ChatMessage chatMessage = 5;</code>
       */
      public cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessage getChatMessage() {
        if (chatMessageBuilder_ == null) {
          return chatMessage_ == null ? cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessage.getDefaultInstance() : chatMessage_;
        } else {
          return chatMessageBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .DataContent.ChatMessage chatMessage = 5;</code>
       */
      public Builder setChatMessage(cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessage value) {
        if (chatMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          chatMessage_ = value;
          onChanged();
        } else {
          chatMessageBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .DataContent.ChatMessage chatMessage = 5;</code>
       */
      public Builder setChatMessage(
              cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessage.Builder builderForValue) {
        if (chatMessageBuilder_ == null) {
          chatMessage_ = builderForValue.build();
          onChanged();
        } else {
          chatMessageBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .DataContent.ChatMessage chatMessage = 5;</code>
       */
      public Builder mergeChatMessage(cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessage value) {
        if (chatMessageBuilder_ == null) {
          if (((bitField0_ & 0x00000010) != 0) &&
                  chatMessage_ != null &&
                  chatMessage_ != cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessage.getDefaultInstance()) {
            chatMessage_ =
                    cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessage.newBuilder(chatMessage_).mergeFrom(value).buildPartial();
          } else {
            chatMessage_ = value;
          }
          onChanged();
        } else {
          chatMessageBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .DataContent.ChatMessage chatMessage = 5;</code>
       */
      public Builder clearChatMessage() {
        if (chatMessageBuilder_ == null) {
          chatMessage_ = null;
          onChanged();
        } else {
          chatMessageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      /**
       * <code>optional .DataContent.ChatMessage chatMessage = 5;</code>
       */
      public cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessage.Builder getChatMessageBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getChatMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .DataContent.ChatMessage chatMessage = 5;</code>
       */
      public cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessageOrBuilder getChatMessageOrBuilder() {
        if (chatMessageBuilder_ != null) {
          return chatMessageBuilder_.getMessageOrBuilder();
        } else {
          return chatMessage_ == null ?
                  cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessage.getDefaultInstance() : chatMessage_;
        }
      }
      /**
       * <code>optional .DataContent.ChatMessage chatMessage = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
              cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessage, cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessage.Builder, cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessageOrBuilder>
      getChatMessageFieldBuilder() {
        if (chatMessageBuilder_ == null) {
          chatMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                  cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessage, cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessage.Builder, cn.tim.xchat.core.model.DataContentSerializer.DataContent.ChatMessageOrBuilder>(
                  getChatMessage(),
                  getParentForChildren(),
                  isClean());
          chatMessage_ = null;
        }
        return chatMessageBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DataContent)
    }

    // @@protoc_insertion_point(class_scope:DataContent)
    private static final cn.tim.xchat.core.model.DataContentSerializer.DataContent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.tim.xchat.core.model.DataContentSerializer.DataContent();
    }

    public static cn.tim.xchat.core.model.DataContentSerializer.DataContent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<DataContent>
            PARSER = new com.google.protobuf.AbstractParser<DataContent>() {
      @java.lang.Override
      public DataContent parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return new DataContent(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DataContent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DataContent> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.tim.xchat.core.model.DataContentSerializer.DataContent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
          internal_static_DataContent_descriptor;
  private static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_DataContent_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
          internal_static_DataContent_ChatMessage_descriptor;
  private static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_DataContent_ChatMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
          descriptor;
  static {
    java.lang.String[] descriptorData = {
            "\n\021DataContent.proto\"\327\001\n\013DataContent\022\016\n\006a" +
                    "ction\030\001 \002(\r\022\020\n\010senderId\030\002 \001(\t\022\021\n\treceive" +
                    "Id\030\003 \001(\t\022\021\n\ttimestamp\030\004 \001(\005\022-\n\013chatMessa" +
                    "ge\030\005 \001(\0132\030.DataContent.ChatMessage\032Q\n\013Ch" +
                    "atMessage\022\014\n\004type\030\001 \002(\r\022\014\n\004text\030\002 \001(\t\022\n\n" +
                    "\002at\030\003 \001(\t\022\013\n\003url\030\004 \001(\t\022\r\n\005reply\030\005 \001(\tB0\n" +
                    "\027cn.tim.xchat.core.modelB\025DataContentSer" +
                    "ializer"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
            new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
              public com.google.protobuf.ExtensionRegistry assignDescriptors(
                      com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                return null;
              }
            };
    com.google.protobuf.Descriptors.FileDescriptor
            .internalBuildGeneratedFileFrom(descriptorData,
                    new com.google.protobuf.Descriptors.FileDescriptor[] {
                    }, assigner);
    internal_static_DataContent_descriptor =
            getDescriptor().getMessageTypes().get(0);
    internal_static_DataContent_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_DataContent_descriptor,
            new java.lang.String[] { "Action", "SenderId", "ReceiveId", "Timestamp", "ChatMessage", });
    internal_static_DataContent_ChatMessage_descriptor =
            internal_static_DataContent_descriptor.getNestedTypes().get(0);
    internal_static_DataContent_ChatMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_DataContent_ChatMessage_descriptor,
            new java.lang.String[] { "Type", "Text", "At", "Url", "Reply", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
